version: '3'

services:
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8880:5432"

volumes:
  pgdata:
